### PR TITLE
feat: workflow update deb repo

### PR DESCRIPTION
**Pull request by 3benbox**
Wanted to simplify the node update process so that they no longer needed Ansible.

A new repo for the debian package was created https://github.com/ceramicnetwork/repo

This workflow publishes rust-ceramic releases to that debian repo.

(need to merge to make sure the gpg stuff works)

### CODE REVIEW

**Review by smrz2001 — APPROVED** [review]
LGTM but should we call the Deb repo something other than `ceramicnetwork/repo` 😂? Is that required for some reason or can it be something more descriptive?

**Comment by 3benbox** [comment]
> LGTM but should we call the Deb repo something other than `ceramicnetwork/repo` 😂? Is that required for some reason or can it be something more descriptive?

Definitely can be changed, and now is the time to do it.
`ceramicnetwork/debian-repo` ?

**Comment by smrz2001** [comment]
> > LGTM but should we call the Deb repo something other than `ceramicnetwork/repo` 😂? Is that required for some reason or can it be something more descriptive?
> 
> Definitely can be changed, and now is the time to do it.
> `ceramicnetwork/debian-repo` ?

Should `ceramic-one` be part of the name somewhere? Just so that the repo is scoped to C1 since that is what the repo is for. Unless it's possible to reuse that repo for other things.

**Comment by 3benbox** [comment]
> > > LGTM but should we call the Deb repo something other than `ceramicnetwork/repo` 😂? Is that required for some reason or can it be something more descriptive?
> > 
> > 
> > Definitely can be changed, and now is the time to do it.
> > `ceramicnetwork/debian-repo` ?
> 
> Should `ceramic-one` be part of the name somewhere? Just so that the repo is scoped to C1 since that is what the repo is for. Unless it's possible to reuse that repo for other things.

The repo can, and should, be used for any other debian packages. cpk maybe? Idk what else, but it can definitely service multiple projects.

I renamed it to `ceramicnetwork/debian-repo`

**Pull request merged**
