### PR TITLE
chore: version v0.25.0

### PR DESCRIPTION
**Pull request by smrz2001**
### 🚀 Features

- Adds migration logic from IPFS (#326)

### 🐛 Bug Fixes

- Adjust API insert contract and avoid failing entire batch if any one is invalid (#388)

### 🚜 Refactor

- Modify store API and rename some things  (#390)

### ⚙️ Miscellaneous Tasks

- Replace tracing_test with test-log and don't init tracing manually (#391)
- Rename prometheus registry and metrics for better consistency (#373)

### CODE REVIEW

**Review by PaulLeCam — APPROVED** [review]

**Comment by oed** [comment]
Why is this still listed as a "pre-release" under releases?
https://github.com/ceramicnetwork/rust-ceramic/releases

**Comment by oed** [comment]
@smrz2001 really like the PR description btw!

**Comment by smrz2001** [comment]
> @smrz2001 really like the PR description btw!

That's just the automation 😅 (and also the release PRs get made in my name because we needed to use a Personal Access Token to workaround GH shenanigans for CD, so I didn't even open this PR 😂)

**Comment by stbrody** [comment]
> Why is this still listed as a "pre-release" under releases? [ceramicnetwork/rust-ceramic/releases](https://github.com/ceramicnetwork/rust-ceramic/releases)

Every new release goes out for a week as a pre-release before being promoted to full release a week later.  This one should become a full release today along with a new pre-release getting made.

**Pull request merged**
